// ---------------------------------------------------------------------------
// §7.1 — BibTeX exporter
// ---------------------------------------------------------------------------

import type { Author, Package, SoftwareCitation } from '@citey/citation-model';
import { escapeLatex } from './escape.js';
import { bibKeyFor, dedupeKeys } from './bibkey.js';

export type BibTeXMeta = {
  extensionVersion: string;
  dbVersion: string;
};

/**
 * Render an array of packages as a complete `.bib` file string.
 *
 * Includes the standard Citey header, followed by one BibTeX entry per
 * package. Every entry uses `@software` (Citey enforces software-only
 * citation per FORCE11).
 *
 * Packages without a `citation` (i.e. `citeAs` aliases) are skipped — the
 * caller is responsible for resolving aliases first.
 */
export function toBibTeX(packages: Package[], meta: BibTeXMeta): string {
  const now = new Date();
  const header = buildHeader(meta, now);

  const citeable = packages.filter((p) => p.citation !== undefined);
  const rawKeys = citeable.map((pkg) => bibKeyFor(pkg));
  const keys = dedupeKeys(rawKeys);

  const entries = citeable.map((pkg, i) => renderEntry(pkg, keys[i]!));

  return header + entries.join('\n\n') + '\n';
}

function buildHeader(meta: BibTeXMeta, now: Date): string {
  const iso = now.toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
  return [
    `% Generated by Citey v${meta.extensionVersion} on ${iso}`,
    `% Database v${meta.dbVersion}`,
    '% UTF-8',
    '',
    '',
  ].join('\n');
}

function renderEntry(pkg: Package, key: string): string {
  const c = pkg.citation!;

  const lines: string[] = [];
  lines.push(`@software{${key},`);
  lines.push(`  author = {${escapeLatex(buildAuthorField(c.authors))}},`);
  lines.push(`  title = {${escapeLatex(c.title)}},`);
  lines.push(`  year = {${escapeLatex(c.year)}},`);
  if (c.version !== undefined) {
    lines.push(`  version = {${escapeLatex(c.version)}},`);
  }
  if (c.doi !== undefined) {
    lines.push(`  doi = {${escapeLatex(c.doi)}},`);
  }
  if (c.url !== undefined) {
    lines.push(`  url = {${escapeLatex(c.url)}},`);
  }
  if (c.publisher !== undefined) {
    lines.push(`  publisher = {${escapeLatex(c.publisher)}},`);
  }
  lines.push('}');

  return lines.join('\n');
}

/**
 * Build the BibTeX `author` field value by joining all authors with ` and `
 * (BibTeX convention). Each author is rendered as `Family, Given`.
 */
function buildAuthorField(authors: SoftwareCitation['authors']): string {
  if (authors.length === 0) {
    return 'Unknown';
  }
  return authors.map((a: Author) => `${a.family}, ${a.given}`.trim()).join(' and ');
}
