// ---------------------------------------------------------------------------
// §7.1 — BibTeX exporter
// ---------------------------------------------------------------------------

import type { Author, Package, SoftwareCitation } from '@citey/citation-model';
import { escapeLatex } from './escape.js';
import { bibKeyFor, dedupeKeys } from './bibkey.js';

export type BibTeXMeta = {
  extensionVersion: string;
  dbVersion: string;
};

/**
 * Per-package Software Heritage extras attached at click time. Passed in
 * parallel with the package list to avoid threading SWH state through every
 * caller. Either field may be absent.
 *
 * - `bibtex`: SWH-rendered BibTeX. When present, emitted verbatim — SWH
 *   already produces a `@softwareversion` entry from biblatex-software with
 *   a qualified SWHID baked in.
 * - `swhid`: live snapshot SWHID. When present (and no `bibtex`), embedded
 *   into the locally-constructed `@software` entry.
 */
export type SwhExtras = {
  bibtex?: string | undefined;
  swhid?: string | undefined;
};

/**
 * Render an array of packages as a complete `.bib` file string.
 *
 * Includes the standard Citey header, followed by one BibTeX entry per
 * package. Locally-constructed entries use `@software` (Citey enforces
 * software-only citation per FORCE11). Entries augmented by Software
 * Heritage are passed through verbatim — SWH typically emits
 * `@softwareversion` from `biblatex-software`.
 *
 * Packages without a `citation` (i.e. `citeAs` aliases) are skipped — the
 * caller is responsible for resolving aliases first.
 *
 * TODO(swh): SWH-rendered BibTeX is preferred for now because the
 * maintainer's `CITATION.cff` is the authoritative source. Long term we
 * want a strict standardized format that we control end-to-end and stop
 * passing SWH output through verbatim.
 */
export function toBibTeX(
  packages: Package[],
  meta: BibTeXMeta,
  swhByPackageId?: ReadonlyMap<string, SwhExtras>,
): string {
  const now = new Date();
  const header = buildHeader(meta, now);

  const citeable = packages.filter((p) => p.citation !== undefined);

  // Compute citation keys only for entries we'll render locally — SWH
  // pass-through entries carry their own keys.
  const localKeys = dedupeKeys(
    citeable.map((pkg) => {
      const swh = swhByPackageId?.get(pkg.id);
      return swh?.bibtex !== undefined ? '' : bibKeyFor(pkg);
    }),
  );

  const entries = citeable.map((pkg, i) => {
    const swh = swhByPackageId?.get(pkg.id);
    if (swh?.bibtex !== undefined) {
      // Pass-through. Trim trailing whitespace/newlines so join('\n\n')
      // produces consistent spacing regardless of how SWH terminated it.
      return swh.bibtex.replace(/\s+$/, '');
    }
    const liveSwhid = swh?.swhid;
    const key = localKeys[i] ?? '';
    return renderEntry(pkg, key, liveSwhid);
  });

  return header + entries.join('\n\n') + '\n';
}

function buildHeader(meta: BibTeXMeta, now: Date): string {
  const iso = now
    .toISOString()
    .replace('T', ' ')
    .replace(/\.\d+Z$/, ' UTC');
  return [
    `% Generated by Citey v${meta.extensionVersion} on ${iso}`,
    `% Database v${meta.dbVersion}`,
    '% UTF-8',
    '',
    '',
  ].join('\n');
}

function renderEntry(pkg: Package, key: string, liveSwhid?: string): string {
  const c = pkg.citation;
  if (c === undefined) return '';

  // SWHID priority: live (current snapshot from SWH at click time) >
  // as-of-admission (frozen in db.json at curation time) > none.
  const swhid = liveSwhid ?? pkg.swhid;

  const lines: string[] = [];
  lines.push(`@software{${key},`);
  lines.push(`  author = {${escapeLatex(buildAuthorField(c.authors))}},`);
  lines.push(`  title = {${escapeLatex(c.title)}},`);
  lines.push(`  year = {${escapeLatex(c.year)}},`);
  if (c.version !== undefined) {
    lines.push(`  version = {${escapeLatex(c.version)}},`);
  }
  if (c.doi !== undefined) {
    lines.push(`  doi = {${escapeLatex(c.doi)}},`);
  }
  if (c.url !== undefined) {
    lines.push(`  url = {${escapeLatex(c.url)}},`);
  }
  if (c.publisher !== undefined) {
    lines.push(`  publisher = {${escapeLatex(c.publisher)}},`);
  }
  if (swhid !== undefined) {
    // biblatex-software field; benign in plain BibTeX (silently ignored
    // when the package isn't loaded). Not LaTeX-escaped: SWHIDs are
    // ASCII-safe and biblatex-software parses the qualified form.
    lines.push(`  swhid = {${swhid}},`);
  }
  lines.push('}');

  return lines.join('\n');
}

/**
 * Build the BibTeX `author` field value by joining all authors with ` and `
 * (BibTeX convention). Each author is rendered as `Family, Given`.
 */
function buildAuthorField(authors: SoftwareCitation['authors']): string {
  if (authors.length === 0) {
    return 'Unknown';
  }
  return authors.map((a: Author) => `${a.family}, ${a.given}`.trim()).join(' and ');
}
