// ---------------------------------------------------------------------------
// §7.2 — Zotero HTML exporter
// ---------------------------------------------------------------------------

import type { Author, Package } from '@citey/citation-model';

export type ZoteroMeta = {
  extensionVersion: string;
  dbVersion: string;
};

/**
 * Generate a self-contained HTML page that Zotero's web translator recognises.
 *
 * Always emits "computer program" / software metadata (Citey is
 * software-only). Packages without a `citation` (citeAs aliases) are
 * skipped.
 */
export function toZoteroHtml(packages: Package[], meta: ZoteroMeta): string {
  const now = new Date();
  const iso = now.toISOString();

  const citeable = packages.filter((p) => p.citation !== undefined);
  const metaTags = citeable.map((pkg) => renderCitationMeta(pkg)).join('\n');
  const sections = citeable.map((pkg) => renderSection(pkg)).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Citey export</title>
${metaTags}
</head>
<body>
<h1>Citey export</h1>
<p>Generated by Citey v${esc(meta.extensionVersion)} on ${esc(iso)} — Database v${esc(meta.dbVersion)}</p>
${sections}
</body>
</html>`;
}

/**
 * Open the Zotero HTML in a new Chrome tab via blob URL.
 * Revokes the URL after 60 seconds to prevent memory leaks.
 */
export function openZoteroHtml(packages: Package[], meta: ZoteroMeta): void {
  const html = toZoteroHtml(packages, meta);
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  chrome.tabs.create({ url });

  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 60_000);
}

// ---------------------------------------------------------------------------
// Per-citation <meta> tags
// ---------------------------------------------------------------------------

function renderCitationMeta(pkg: Package): string {
  const c = pkg.citation!;
  const lines: string[] = [];
  lines.push(`<meta name="citation_title" content="${esc(c.title)}">`);

  for (const author of c.authors) {
    lines.push(
      `<meta name="citation_author" content="${esc(`${author.family}, ${author.given}`.trim())}">`,
    );
  }

  lines.push(`<meta name="citation_date" content="${esc(c.year)}">`);

  if (c.doi !== undefined) {
    lines.push(`<meta name="citation_doi" content="${esc(c.doi)}">`);
  }
  if (c.publisher !== undefined) {
    lines.push(`<meta name="citation_publisher" content="${esc(c.publisher)}">`);
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Per-citation <section>
// ---------------------------------------------------------------------------

function renderSection(pkg: Package): string {
  const c = pkg.citation!;
  const byline = c.authors.map((a: Author) => `${a.given} ${a.family}`.trim()).join(', ');

  let linkHtml = '';
  if (c.doi !== undefined) {
    linkHtml = `\n<p><a href="https://doi.org/${esc(c.doi)}">${esc(c.doi)}</a></p>`;
  } else if (c.url !== undefined) {
    linkHtml = `\n<p><a href="${esc(c.url)}">${esc(c.url)}</a></p>`;
  }

  const coins = renderCoins(pkg);

  return `<section class="citation">
<h2>${esc(c.title)}</h2>
<p>${esc(byline)}</p>
<p>${esc(pkg.description)}</p>${linkHtml}
${coins}
</section>`;
}

// ---------------------------------------------------------------------------
// COinS span (Zotero's classic affordance) — always "software" genre
// ---------------------------------------------------------------------------

function renderCoins(pkg: Package): string {
  const c = pkg.citation!;
  const fields: string[] = [];
  fields.push('ctx_ver=Z39.88-2004');
  fields.push('rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc');
  fields.push('rft.genre=software');

  fields.push(`rft.atitle=${encodeURIComponent(c.title)}`);

  for (const author of c.authors) {
    fields.push(
      `rft.au=${encodeURIComponent(`${author.family}, ${author.given}`.trim())}`,
    );
  }

  fields.push(`rft.date=${encodeURIComponent(c.year)}`);

  if (c.doi !== undefined) {
    fields.push(`rft_id=info%3Adoi%2F${encodeURIComponent(c.doi)}`);
  }

  const query = fields.join('&');
  return `<span class="Z3988" title="${esc(query)}"></span>`;
}

// ---------------------------------------------------------------------------
// HTML helpers
// ---------------------------------------------------------------------------

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
